name: Benchmark

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-cpu=native"

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      
      - name: Install criterion dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gnuplot
      
      - name: Run benchmarks
        run: cargo bench -- --output-format bencher | tee benchmark-results.txt
      
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: benchmark-results.txt
          # Publish to GitHub Pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          # Enable alert commit comment
          alert-comment-cc-users: '@${{ github.actor }}'
